theme: jekyll-theme-slate
title: The Top 100 Theorems in Isabelle
description:
baseurl: /100isabelle

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax

plugins:
 - jekyll-coffeescript
 - jekyll-default-layout
 - jekyll-gist
 - jekyll-optional-front-matter
 - jekyll-paginate
 - jekyll-readme-index
 - jekyll-titles-from-headings
 - jekyll-relative-links
